### ISSUE TITLE
Windows user here, don't know anything about anything, help

### ISSUE THREAD

**Issue by elanhickler** [djmcgill/dominions-5-status#73]
I got to this part of the instructions:

Run the command: docker run -it -d --restart unless-stopped -v /home/dmcgill9071/dom-5-bot/resources:/usr/src/myapp/resources --log-opt max-size=10m --log-opt max-file=5 eu.gcr.io/dom-5-status/dom-5-status except replace /home/dmcgill9071/dom-5-bot/resources with the location of your resource folder.

No idea what any of that is and of course docker is a Mac thing.

I don't know anything about bots. Installed rust for the first time. I'm stuck.

**Comment by djmcgill** [comment]
Good news, docker works just fine on windows! You don't need Rust installed
to just use it via docker.
https://docs.docker.com/docker-for-windows/
Try following the install docker desktop for windows instructions here and
let me know if you get stuck.

**Comment by elanhickler** [comment]
Ok, so there are two sets of instructions, one with docker, one with rust. It would be more clear if you changed the instructions to:

To run in using Rust:

To run using Docker:

Alright, so I tried Docker and ran into the error:

> You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication.

Ok, maybe let's not go down the Docker route, I have no idea how any of this works. I seemed to have gotten farther with Rust. The problem with Rust is that the bot doesn't respond to any commands in discord even though it shows as online in my server.

**Comment by djmcgill** [comment]
That's a good point about the instructions. I'm surprised it worked so easily just compiled in rust I guess it's probably easier on windows. I assume you did the token stuff if it seems to be working, and you can check the logs in the console to see if it's detecting incoming commands and/or erroring.

**Comment by elanhickler** [comment]
How do you make the bot only respond in specific channels?

**Comment by djmcgill** [comment]
There is no way to currently do that, the easiest way if you're having clashing issues would be to change its prefix character. If you did prefer to make it only respond to specific channels I'd be happy to walk you through it. To change the prefix character you'll want to look at the file src/main.rs line 104: https://github.com/djmcgill/dominions-5-status/blob/master/src/main.rs#L104

**Comment by elanhickler** [comment]
ok, so I used !add command, !list command works, I set !notifications true. It's still not announcing new turns. How do I make it announce new turns?

**Comment by djmcgill** [comment]
Does the !details command work? If so, use the !register command for your
nation, and run !details again and it should show that you're registered as
that nation. You should them get DMs for new turns. The bot doesn't yet
have functionality to announce in channels, it DMs anybody who has
registered.

**Comment by elanhickler** [comment]
Ok, it works. Suggestions:

I was confused because it said !register nation_prefix. I don't know where to find the nation prefix. So it is less confusing if it would simply say something like:

>`!register nation <alias>: register yourself as a nation in a game`

Also, for id I added "use !details to get id":

>`!register-id nation_id <alias>: register yourself as a nation in a game using the id, use details command to get id`

**Comment by djmcgill** [comment]
Okay, good to hear. I've already edited the readme with the "running with
rust" suggestion earlier. By the "nation prefix" I mean that you don't have
to use the whole nation name, so e.g. "!register mict" works. Is there a
better way to phrase that?

Do note that if you're in a channel with the same name as the alias that
you gave the bot, then you can skip the channel name in any commands.

Finally the thing that first inspired me to write the bot was getting
annoyed at having to look up nation IDs. Register-id is only intended to be
used for mod games, if you have trouble with the normal register command
for vanilla nations please let me know.

Anyway I'm glad it's working for you now. If you want to run it on a
server, then I do recommend you look into docker. I'm going to close this
issue now (you can still reply).

>
