### ISSUE TITLE
Need a way to send out notification manually for new turn

### ISSUE THREAD

**Issue by elanhickler** [djmcgill/dominions-5-status#75]
The bot was offline when the turn ran. Need to manually send out that notification. Or make the bot recognize if the current turn number does not match with the bot's last notification.

Edit: I mean I just want to send out the notification where it says how much time is left. Nothing new.

**Comment by djmcgill** [comment]
Hmm, you're right this is not well handled. 

I guess my first question is quite a dumb one: are you sure that no notification gets sent? There is _supposed_ to be some code that detects when the turn on the server is newer than the turn on the database and sends a notification - so it _shouldn't_ matter. However I can totally accept that that bit of code is not working, or I've had other issues like e.g. discord being down that prevent the messages from getting through. Was it the first turn that was an issue or some later turn?

My second point, is that the bot is not really designed to be run on a desktop and to go up and down, I'd really recommend running it on a server 24/7 - it, inside docker, fits quite comfortably inside Google Cloud Platform's free tier for example that's how I'm running my copy.

Thirdly, there is a not very nice hack to "force" the bot to update a turn. If you use [url=https://sqlite.org/download.html](SQLite) you can manually modify the bot's database file to change a saved turn number back to an old one and then when it next connects to the server it'll see a new turn and send out notifications. If you want to try this but are not familiar with SQL I'm happy to walk you through it, and if you are familiar with SQL then you can look up the game name (or alias) in the `game_servers` table and then join on `game_servers.started_server_id` to `started_servers.id` and modify `started_servers.last_seen_turn`. This is obviously not something you'd want to be doing regularly.

Fourthly, if the notification definitely doesn't get sent, I don't suppose you could paste the logs that happen when the bot first turns on and then connects to your game after a turn has passed? Like I said there IS some code that is supposed to handle this so I'm interested why it's not working. Feel free to strip IP addresses or whatever if they're in there.

**Comment by elanhickler** [comment]
Apparently everyone got a notification except me. Will have to call this an anomaly. No idea what happened.

**Comment by djmcgill** [comment]
Ha! Well that's a relief I suppose.
